### ISSUE TITLE
Recommendation links not shown in site

### ISSUE THREAD

**Issue by sixeyed** [lgmorand/aks-checklist#252]
There are links in all the items in the source JSON but they aren't shown in the site (that I can see). It would be great to have those links to the docs for people who aren't familiar with the recommendation.

**Comment by lgmorand** [comment]
Refresh the page and look at the tooltip 😉

There is an arrow in front of each item. Click on it

**Comment by sixeyed** [comment]
So there is, thank you. Do you think it would be better to default details to show and have the option to hide them? Then you wouldn't get issues like this :)

**Comment by lgmorand** [comment]
long debate with people but also in my head :D but no.
- No because it then takes too much space when expanded and it prevents the readability
- It's worked for years like on other websites using the same template (I just copied it)
- That's why I added the tooltips and changed the color of buttons. From the metrics, since I put these improvments in place, people seem to be able to find it.


But if you find a good UI way to tell people, "you can expand", don't hesitate. there is always improvement and feedback are always welcome :)

**Comment by lgmorand** [comment]
I could add clippy : https://www.smore.com/clippy-js

:D
